### ISSUE TITLE
Add "show" prop to README documentation.

### ISSUE THREAD

**Issue by josuezambrano** [vtex-apps/disposition-layout#1]
Hello, can you add the prop "show" to the README or documentation please?
I was searching for hide items by default but i was thinking this not possible until i look the code.
![image](https://user-images.githubusercontent.com/86591680/138266161-f2f317df-6d98-4a01-8b37-d48b0f99c6ae.png)
![image](https://user-images.githubusercontent.com/86591680/138265636-c24dcb79-07cf-47de-9db4-4d336d52d2c0.png)

**Comment by Git-the-Sanz** [comment]
The prop was left out on purpose. It only serves as the foundation to hide them via site editor. It's bound to the content and not the the actual prop passed via store-framework

**Comment by josuezambrano** [comment]
@Git-the-Sanz  I understand no problem. I just comment this because maybe will be useful for develeper will know this prop. In us case we were needed hide a block by default and the client take the decision when he want show it and we had look in the code to know is possible. 

I would like to ask if is possible to restore a item deleted in admin. I searched a solution but I didn't find it.

Thanks in advance

**Comment by Git-the-Sanz** [comment]
Yes! The site editor has a 'configuration' tab for each component. You can `revert` back to the original store-framework implementation. That's also the reason why everything is shown by default, so it's easier to track everything when going back to the default content.
